import type { Pizza, Drink, PizzaAddon, PizzaSizeOption } from '@/types';

export const PIZZA_ADDONS: PizzaAddon[] = [
  { id: 'addon-1', name: 'Extra Cheese', price: 2.00 },
  { id: 'addon-2', name: 'Pepperoni', price: 2.50 },
  { id: 'addon-3', name: 'Mushrooms', price: 1.50 },
  { id: 'addon-4', name: 'Olives', price: 1.50 },
  { id: 'addon-5', name: 'Onions', price: 1.00 },
  { id: 'addon-6', name: 'Bacon', price: 3.00 },
];

export const PIZZA_SIZES: PizzaSizeOption[] = [
  { id: 'size-s', name: 'Small (10")', price: 0, diameterInches: 10 },
  { id: 'size-m', name: 'Medium (12")', price: 3.00, diameterInches: 12 }, // Additional cost for medium
  { id: 'size-l', name: 'Large (14")', price: 6.00, diameterInches: 14 }, // Additional cost for large
];


export const PIZZAS_DATA: Pizza[] = [
  {
    id: 'pizza-1',
    name: 'Margherita',
    description: 'Classic delight with San Marzano tomatoes, mozzarella fior di latte, fresh basil, and a drizzle of olive oil.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'pizza margherita',
    basePrice: 12.99,
    sizes: PIZZA_SIZES,
    availableAddons: PIZZA_ADDONS,
    category: 'Vegetarian',
  },
  {
    id: 'pizza-2',
    name: 'Pepperoni',
    description: 'A crowd-pleaser with generous layer of spicy pepperoni and mozzarella cheese.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'pizza pepperoni',
    basePrice: 14.99,
    sizes: PIZZA_SIZES,
    availableAddons: PIZZA_ADDONS,
    category: 'MeatLover',
  },
  {
    id: 'pizza-3',
    name: 'Quattro Formaggi',
    description: 'A cheese lover’s dream with a blend of four Italian cheeses: mozzarella, gorgonzola, ricotta, and parmigiano.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'pizza cheese',
    basePrice: 15.99,
    sizes: PIZZA_SIZES,
    availableAddons: PIZZA_ADDONS,
    category: 'Vegetarian',
  },
  {
    id: 'pizza-4',
    name: 'Capricciosa',
    description: 'A rich pizza with tomato sauce, mozzarella, mushrooms, artichokes, cooked ham, olives, and basil.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'pizza varied',
    basePrice: 16.99,
    sizes: PIZZA_SIZES,
    availableAddons: PIZZA_ADDONS,
  },
  {
    id: 'pizza-5',
    name: 'Diavola',
    description: 'Spicy salami, chili flakes, and mozzarella cheese for those who like it hot.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'pizza spicy',
    basePrice: 15.50,
    sizes: PIZZA_SIZES,
    availableAddons: PIZZA_ADDONS,
    category: 'MeatLover',
  },
  {
    id: 'pizza-6',
    name: 'Vegetariana',
    description: 'Loaded with fresh seasonal vegetables like bell peppers, zucchini, eggplant, and olives over a tomato and mozzarella base.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'pizza vegetarian',
    basePrice: 14.50,
    sizes: PIZZA_SIZES,
    availableAddons: PIZZA_ADDONS,
    category: 'Vegetarian',
  },
  {
    id: 'pizza-7',
    name: 'Prosciutto e Funghi',
    description: 'A classic combination of cooked ham and savory mushrooms on a bed of mozzarella and tomato sauce.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'pizza ham mushroom',
    basePrice: 15.99,
    sizes: PIZZA_SIZES,
    availableAddons: PIZZA_ADDONS,
  },
  {
    id: 'pizza-8',
    name: 'Marinara',
    description: 'Simple yet flavorful with San Marzano tomatoes, garlic, oregano, and extra virgin olive oil (no cheese).',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'pizza marinara',
    basePrice: 10.99,
    sizes: PIZZA_SIZES,
    availableAddons: PIZZA_ADDONS,
    category: 'Vegan',
  },
  {
    id: 'pizza-9',
    name: 'Napolitana',
    description: 'The true taste of Naples: San Marzano tomatoes, mozzarella di bufala, fresh basil, and olive oil.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'pizza naples',
    basePrice: 17.99,
    sizes: PIZZA_SIZES,
    availableAddons: PIZZA_ADDONS,
  },
  {
    id: 'pizza-10',
    name: 'Calzone Classico',
    description: 'A folded pizza stuffed with ricotta, mozzarella, salami, and cooked ham, baked to perfection.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'pizza calzone',
    basePrice: 16.50,
    sizes: [{ id: 'size-calzone', name: 'Standard', price: 0 }], // Calzones usually one size
    availableAddons: PIZZA_ADDONS.slice(0,3), // Limited addons for calzone
  },
];

export const DRINKS_DATA: Drink[] = [
  {
    id: 'drink-1',
    name: 'Coca-Cola',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'drink soda',
    price: 2.50,
    volume: '330ml Can',
    category: 'Soft Drink',
  },
  {
    id: 'drink-2',
    name: 'San Pellegrino Sparkling Water',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'drink water',
    price: 3.00,
    volume: '500ml Bottle',
    category: 'Water',
  },
  {
    id: 'drink-3',
    name: 'Peroni Nastro Azzurro',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'drink beer',
    price: 5.00,
    volume: '330ml Bottle',
    category: 'Beer',
  },
  {
    id: 'drink-4',
    name: 'Chianti Classico (Glass)',
    description: 'A smooth red wine from Tuscany.',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'drink wine',
    price: 7.00,
    volume: '150ml Glass',
    category: 'Wine',
  },
  {
    id: 'drink-5',
    name: 'Fresh Orange Juice',
    imageUrl: 'https://placehold.co/300x300.png',
    imageHint: 'drink juice',
    price: 4.00,
    volume: '300ml Glass',
    category: 'Juice',
  },
];
